### ISSUE TITLE
Path concatenation issue on Mac/Linux while running CxAnalytixDaemon 

### ISSUE THREAD

**Issue by kmcdon83** [checkmarx-ts/CxAnalytix#13]
### Description

The initial run is concatenating paths, and the initial path is `.\`, which is causing an issue during writing of the State file.

### Expected Behavior

File path should be proper format

### Actual Behavior

.\ is concatenated with issues, causing exception (see below).

### Reproduction

Execution of the Linux Daemon on Mac, Linux (WSL 2), the following exception occurs:
```
[2020-07-10 12:23:15,197] ERROR [4] [CxAnalytix.TransformLogic.Transformer] (?:?) - Error resolving scans, server may be unavailable.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/App/.\/CxAnalytixExportState.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at CxAnalytix.TransformLogic.ProjectResolver.saveProjectCheckState() in /Users/kenmcdonald/Documents/checkmarx-ts/cxanalytix/TransformLogic/ProjectResolver.cs:line 85
   at CxAnalytix.TransformLogic.ScanResolver.Resolve(DateTime lastCheckDate) in /Users/kenmcdonald/Documents/checkmarx-ts/cxanalytix/TransformLogic/ScanResolver.cs:line 145
   at CxAnalytix.TransformLogic.Transformer..ctor(CxRestContext ctx, CancellationToken token, String previousStatePath) in /Users/kenmcdonald/Documents/checkmarx-ts/cxanalytix/TransformLogic/Transformer.cs:line 328
```

### Environment Details

Confirmed on Mac, Docker on mac, WSL 2

**Comment by kmcdon83** [comment]
PR is being submitted shortly with the fix.

**Comment by kmcdon83** [comment]
Closing as this value can be changed in the application config, which solves the problem:
 ``` <CxAnalyticsService ConcurrentThreads="2" StateDataStoragePath=".\"```
to
  ```<CxAnalyticsService ConcurrentThreads="2" StateDataStoragePath=""```
