### ISSUE TITLE
Policy violation retrieval error with a 9.0 server.

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ts/CxAnalytix#18]
### Description

Trying to retrieve policy violations from projects with a 9.0 server results in the following errors and no policy violation data being retrieved.

[2020-07-16T09:24:39-05:00][ WARN][1][CxAnalytix.TransformLogic.Transformer] Unable to correlate policies to project 15: SimplyVulnerable-master. Policy statistics will be unavalable.
System.InvalidOperationException: Unable to retrieve policies for project 15.
   at CxRestClient.CxMnoPolicies.GetPolicyIdsForProject(CxRestContext ctx, CancellationToken token, Int32 projectId) in /root/project/CxRestClient/CxMnoPolicies.cs:line 156
   at CxAnalytix.TransformLogic.Transformer..ctor(CxRestContext ctx, CancellationToken token, String previousStatePath) in /root/project/TransformLogic/Transformer.cs:line 288

[2020-07-16T09:24:41-05:00][DEBUG][1][CxAnalytix.TransformLogic.Transformer] Policy violations for project 15: SimplyVulnerable-master are unavailable.
System.InvalidOperationException: Unable to retrieve rule violations for project 15.
   at CxRestClient.CxMnoRetreivePolicyViolations.GetViolations(CxRestContext ctx, CancellationToken token, Int32 projectId, PolicyCollection policies) in /root/project/CxRestClient/CxMnoRetreivePolicyViolations.cs:line 118
   at CxAnalytix.TransformLogic.Transformer.<ExecuteSweep>b__74_0(ScanDescriptor scan) in /root/project/TransformLogic/Transformer.cs:line 354

### Expected Behavior

If there are policy violations available, they should be retrieved.

### Actual Behavior

No policy violations reported.

### Reproduction

Execute against a 9.0 server.

### Environment Details

Windows client, 9.0 server,

**Comment by nleach999** [comment]
Prior to 9.0, accessing the cxarm API only required the cxarm_api scope.  It looks like it now passes the JWT from the client over to the rest API which gives a generic error because it also needs the sast_rest_api scope to resolve projects.  Testing will be done to ensure backwards compatibility to 8.9 and 8.9/9.0 without the cxarm_api scope installed (no M&O installed and/or no license).
