### ISSUE TITLE
Unable to obtain login token due to an unexpected exception

### ISSUE THREAD

**Issue by leonsnoopy** [checkmarx-ts/CxAnalytix#98]
Environment : 
Windows Server 2012R2
Dotnet 3.1 runtime
Checkmarx 890 HF30 / 920 HF17

Description：
I try many times to set the config in Environmental variables or inline but it always fails in login token issue, the log message is below...

[2021-08-12T11:19:28+08:00][ INFO][1][CxAnalytixCLI.Program] Start
[2021-08-12T11:19:28+08:00][ INFO][1][CxAnalytixCLI.Program] CWD: C:\Users\Administrator\Desktop\CxAnalytix1.3.1-560.win-x64
[2021-08-12T11:19:28+08:00][ WARN][1][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Not Found
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
[2021-08-12T11:19:28+08:00][ WARN][1][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Not Found
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146

And the same at the Checkmarx 920. Is it support the 9.2 version?

Thanks.

**Comment by nleach999** [comment]
@leonsnoopy CxAnalytix does support 9.2.  That message indicates the URL it is accessing could not be found (404 error).  Check to make sure the URL to SAST is not including "cxwebclient".

**Comment by leonsnoopy** [comment]
sorry...for the late
I change the URL not including "cxwebclient" is the same.
but i found a error message in the log.

..........
[2021-09-16T15:14:36+08:00][ INFO][1][CxAnalytixCLI.Program] Start
[2021-09-16T15:14:36+08:00][ INFO][1][CxAnalytixCLI.Program] CWD: C:\Users\Administrator\Desktop\CxAnalytix1.3.1-560.win-x64
[2021-09-16T15:14:36+08:00][ WARN][1][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Bad Request
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
[2021-09-16T15:14:36+08:00][ WARN][4][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Bad Request
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
[2021-09-16T15:14:36+08:00][ WARN][4][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Bad Request
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
[2021-09-16T15:14:36+08:00][ERROR][4][CxRestClient.Utility.WebOperation] Exception: System.ArgumentException Source: System.Net.Http Message: The value cannot be null or empty. (Parameter 'scheme') - Retrying until 2021/9/16 下午 03:24:36
[2021-09-16T15:14:39+08:00][ WARN][4][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Bad Request
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
[2021-09-16T15:14:39+08:00][ WARN][4][CxRestClient.CxRestContext] Unable to obtain login token due to an unexpected exception.  Login will retry on the next operation.
System.InvalidOperationException: Bad Request
   at CxRestClient.CxRestContext.GetLoginToken(String url, HttpContent authContent) in /root/project/CxRestClient/CxRestContext.cs:line 146
..........

**Comment by nleach999** [comment]
@leonsnoopy You may want to enable [network trace loggin](https://github.com/checkmarx-ts/CxAnalytix/wiki/Troubleshooting) to see if it will show you the request that the server is considering "bad" (thus the 400 Bad Request response).  

If you have a proxy server, you may need to set the [ALL_PROXY](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=netcore-3.1#remarks) environment variable.

**Comment by nleach999** [comment]
This may have been due to the way M&O was not handled well when not installed.  Reopen with more details if the issues persists.  All indications are this is not an issue any longer if it was not originally due to configuration.
